name: deploy
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Версия для деплоя (1, 2, 13 …)"
        required: true

jobs:
  prod:
    runs-on: ubuntu-latest
    env:
      IMAGE: cr.yandex/${{ secrets.YC_REGISTRY }}/app:${{ inputs.version }}_latest
    steps:
      - name: login to container registry
        run: |
          IMAGE="cr.yandex/${{ secrets.YC_REGISTRY }}/app:${{ inputs.version }}_latest"
          docker login cr.yandex -u oauth -p ${{ secrets.YC_OAUTH_TOKEN }}
          docker manifest inspect "$IMAGE" >/dev/null

      - name: deploy to vm
        uses: appleboy/ssh-action@v1
        with:
          host:     ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key:      ${{ secrets.VM_SSH_KEY }}
          script: |
            IMAGE="cr.yandex/${{ secrets.YC_REGISTRY }}/app:${{ inputs.version }}_latest"

            docker login cr.yandex -u oauth -p '${{ secrets.YC_OAUTH_TOKEN }}'
            docker pull "$IMAGE"

            docker stop app || true && docker rm app || true
            docker run -d --name app -p 80:3000 "$IMAGE"

      - name: open deploy issue
        run: |
          ISSUE=$(gh issue list \
                    --state all \
                    --search "Release ${{ inputs.version }}" \
                    --json number \
                    -q '.[0].number')

          if [ -n "$ISSUE" ]; then
            gh issue comment "$ISSUE" \
              --body "**🚀 Выкат в прод**: $(date)\n**Автор:** ${{ github.actor }}"
          else
            echo "⚠️  Issue 'Deploy ${{ inputs.version }}' не найден."
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}